const guide = {
  service: "OKRPTR Codex conversation API",
  version: "1.1",
  authentication: {
    header: "Authorization: Bearer <OKRPTR_ACCESS_TOKEN>",
    note: "The token is scoped to one OKRPTR workspace. Never print or persist it in source files or logs.",
  },
  hierarchy: "OKR: Objective > Key Result > Initiative > Project > Task. Routine is an independent Project-like container and may own Tasks without an Initiative.",
  values: {
    kind: ["objective", "key_result", "initiative", "project", "task"],
    status: ["backlog", "todo", "policy_discussion", "in_progress", "developing", "development_done", "done", "blocked", "archived"],
    priority: ["low", "medium", "high", "urgent"],
    cadence: ["daily", "weekly", "monthly", "quarterly"],
  },
  endpoints: [
    { purpose: "Read workspace name and current role", method: "GET", path: "/api/team" },
    { purpose: "Read shared capture and structure rules", method: "GET", path: "/api/workspace-rules" },
    { purpose: "Update shared rules", method: "PUT", path: "/api/workspace-rules", body: "Any of captureInstruction, structureInstruction, routineInstruction, defaultPriority, defaultCadence, reviewBeforeCreate" },
    { purpose: "List or search active items", method: "GET", path: "/api/items?kind=&status=&cadence=&parentId=&q=&includeArchived=false" },
    { purpose: "Create an item", method: "POST", path: "/api/items", body: "title required; optional description, kind, cycleId, parentId, routineId, status, priority, cadence, progress, dueDate, driMemberId, workerMemberIds, assigneeMemberId, and Project-only templateId; use source=codex" },
    { purpose: "Update or link an item", method: "PATCH", path: "/api/items", body: "id required; include only fields to change, including parentId or routineId" },
    { purpose: "List OKR files/cycles", method: "GET", path: "/api/okr-cycles" },
    { purpose: "Create an OKR cycle", method: "POST", path: "/api/okr-cycles", body: "name, department, startDate, endDate, status" },
    { purpose: "Update an OKR cycle", method: "PATCH", path: "/api/okr-cycles", body: "id required plus changed fields" },
    { purpose: "List routines", method: "GET", path: "/api/routines?date=YYYY-MM-DD&includeInactive=true" },
    { purpose: "Create a routine", method: "POST", path: "/api/routines", body: "title required; triggerPoint, actionPlace, actionSteps, cadence, active" },
    { purpose: "Update a routine", method: "PATCH", path: "/api/routines", body: "id required plus changed fields" },
    { purpose: "Delete a routine after explicit confirmation", method: "DELETE", path: "/api/routines?id=<routine-id>", requiresConfirmation: true },
    { purpose: "Read or update today's scrum", method: "GET or PUT", path: "/api/daily-scrum?date=YYYY-MM-DD", body: "For PUT: date, yesterdayNote, todayNote, blockersNote" },
    { purpose: "Complete or reopen a routine for a date", method: "PUT or DELETE", path: "/api/routine-completions", body: "routineId and date required; note optional" },
    { purpose: "Archive a Project and its direct Tasks", method: "POST", path: "/api/project-archives", body: "projectId required" },
    { purpose: "List archived Projects", method: "GET", path: "/api/project-archives" },
    { purpose: "Restore a Project and its direct Tasks", method: "DELETE", path: "/api/project-archives?projectId=<project-id>" },
    { purpose: "Permanently delete an archived Project and all of its archived Tasks after explicit confirmation", method: "DELETE", path: "/api/project-archives/permanent", body: "projectId and exact confirmationTitle required", requiresConfirmation: true },
    { purpose: "Read active or inactive Project property definitions, defaults, values, and per-Project visibility", method: "GET", path: "/api/properties?includeInactive=false" },
    { purpose: "Create a Project property", method: "POST", path: "/api/properties", body: "name and type required; optional options and defaultValue" },
    { purpose: "Preview a property type conversion", method: "PATCH", path: "/api/properties", body: "id, preview=true, and type; returns convertible and incompatible value counts" },
    { purpose: "Update, reorder, remove, or restore a Project property definition", method: "PATCH or DELETE", path: "/api/properties", body: "PATCH requires id and changed name, type, options, defaultValue, sortOrder, or active. DELETE soft-removes by id and preserves values" },
    { purpose: "Set one Project property value", method: "PATCH", path: "/api/property-values", body: "itemId, propertyId, value" },
    { purpose: "Set Project or Task member assignments", method: "PATCH", path: "/api/item-assignments", body: "itemId, role, memberIds; role is project_dri, project_worker, or task_assignee" },
    { purpose: "Hide or show a property on one Project", method: "PATCH", path: "/api/project-property-visibility", body: "projectId, propertyId, hidden" },
    { purpose: "Read a Project block document and current version", method: "GET", path: "/api/project-documents?projectId=<project-id>" },
    { purpose: "Save a Project block document with conflict detection", method: "PUT", path: "/api/project-documents", body: "projectId, BlockNote-compatible content JSON, plainText, and expectedVersion" },
    { purpose: "Apply a body template above existing Project content", method: "POST", path: "/api/project-documents", body: "projectId and templateId" },
    { purpose: "List, create, update, or delete Project body templates", method: "GET, POST, PATCH or DELETE", path: "/api/project-templates", body: "Templates contain name, optional description, BlockNote-compatible content JSON, and plainText; DELETE uses id query", requiresConfirmationForDelete: true },
    { purpose: "Read or manage a Task checklist", method: "GET, POST, PATCH or DELETE", path: "/api/checklists?taskId=<task-id>", body: "POST requires taskId and title; PATCH requires id; DELETE uses id query", requiresConfirmationForDelete: true },
    { purpose: "Read workspace groups", method: "GET", path: "/api/groups" },
    { purpose: "Create or update a workspace group", method: "POST or PATCH", path: "/api/groups", body: "POST requires name; PATCH requires id; optional handle, description, color, visibility, archived" },
    { purpose: "Read team members", method: "GET", path: "/api/team" },
    { purpose: "Read recommendations", method: "GET", path: "/api/recommendations" },
    { purpose: "Delete an OKR cycle after explicit confirmation", method: "DELETE", path: "/api/okr-cycles?id=<cycle-id>", requiresConfirmation: true },
    { purpose: "Delete a group after explicit confirmation", method: "DELETE", path: "/api/groups?id=<group-id>", requiresConfirmation: true },
  ],
  behavior: [
    "Fetch workspace rules before interpreting unstructured work.",
    "Use General Task capture when no Project or named Routine is known.",
    "Treat Project templates as body-only copies: never infer or copy properties, assignments, or Tasks from a template.",
    "For counts, fetch items once and group locally by kind; fetch routines separately.",
    "Do not delete cycles, routines, groups, members, or workspace data without immediate user confirmation.",
    "Return concise summaries instead of raw JSON unless raw data is requested.",
  ],
};

export function GET() {
  return Response.json(guide, {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "public, max-age=300",
    },
  });
}
